const toOptions = (arr) =>
  arr.map((item) => ({
    label: item,
    value: item.toLowerCase().replace(/\s+/g, "-"),
  }));

const toValuesOnly = (arr) => arr.map((item) => item);

export const MaritalStatus = toOptions([
  "Un-married",
  "Married",
  "Brahmchari",
  "Widowed",
]);

export const InitiationStatus = toOptions([
  "Non-initiated",
  "Harinam-initiated",
  "Brahman-initiated",
  "Sanyas-initiated",
]);

export const skillsOptions = toOptions([
  "Software",
  "Hardware",
  "Teaching",
  "Public Speaking",
  "Cooking",
  "Event Management",
  "Accounting",
  "Management",
  "Leadership",
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Social Media",
  "Content Writing",
  "Translation",
  "Sanskrit",
  "Kirtan",
  "Mridanga",
  "Harmonium",
  "Book Distribution",
  "Preaching",
  "Counselling",
  "Fundraising",
  "Marketing",
  "Sales",
  "Driving",
  "Electric Work",
  "Plumbing",
  "Carpentry",
  "Gardening",
  "Agriculture",
  "Cow Care",
  "Cleaning",
  "Decoration",
  "Data Entry",
  "Excel",
  "Administration",
  "Security",
  "First Aid",
  "Health Care",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Networking",
  "Audio/Sound Management",
  "Stage Management",
  "Hospitality",
  "Communication",
  "Team Coordination",
  "Time Management",
]);

export const books = toOptions([
  "Bhagavad-gita As It Is",
  "Srimad Bhagavatam",
  "Sri Caitanya-caritamrta",
  "Teachings of Lord Caitanya",
  "The Nectar of Devotion",
  "The Nectar of Instruction",
  "Sri Isopanisad",
  "Easy Journey to Other Planets",
  "Krsna Book",
  "Beyond Birth and Death",
  "Perfect Questions, Perfect Answers",
  "Life Comes From Life",
  "Elevation to Krsna Consciousness",
  "On the Way to Krsna",
  "Raja Vidya: The King of Knowledge",
  "Science of Self-Realization",
  "Message of Godhead",
  "Path of Perfection",
  "Civilization and Transcendence",
  "Teachings of Queen Kunti",
  "Krsna Consciousness: The Topmost Yoga System",
  "Transcendental Teachings of Prahlad Maharaj",
  "Coming Back",
  "Matchless Gifts",
  "Narada Bhakti Sutra",
  "Renunciation Through Wisdom",
  "Journey of Self Discovery",
  "Light of the Bhagavata",
  "Mukunda Mala Stotra",
  "The Perfection of Yoga",
  "The Laws of Nature",
  "The Science of Reincarnation",
  "The Journey Home",
  "The Hare Krishna Challenge",
]);

export const IskconDikshaGurus = toValuesOnly([
  "A. C. Bhaktivedanta Swami Prabhupada",
  "Jayapataka Swami",
  "Gopal Krishna Goswami",
  "Radhanath Swami",
  "Lokanath Swami",
  "Giriraj Swami",
  "Bhakti Vikasa Swami",
  "Indradyumna Swami",
  "Sivarama Swami",
  "Romapada Swami",
  "Bhakti Purusottama Swami",
  "Bhakti Vijnana Goswami",
  "Bhanu Swami",
  "Devamrita Swami",
  "Mahanidhi Swami",
  "Niranjana Swami",
  "Prahladananda Swami",
  "Rtadhvaja Swami",
  "Hridayananda Goswami",
  "Sacinandana Swami",
  "Subhag Swami",
  "Candramauli Swami",
  "Guru Prasada Swami",
  "Bhakti Bringa Govinda Swami",
  "Bhakti Raghava Swami",
  "Bhakti Vaibhava Swami",
  "Bhakti Madhurya Govinda Swami",
]);

export const Counselors = toValuesOnly([
  "H.G Satyayug prabhu",
  "H.G Luvkush prabhu",
  "H.G Kirtanand prabhu",
  "H.G gaur govind prabhu",
  "H.G sankirtan chaitanya prabhu",
  "H.G Anant shyam prabhu",
]);

export const Occupations = toOptions([
  "Student",
  "Teacher",
  "Professor",
  "Software Engineer",
  "Web Developer",
  "Mobile App Developer",
  "UI/UX Designer",
  "Graphic Designer",
  "Video Editor",
  "Photographer",
  "Content Writer",
  "Digital Marketer",
  "Accountant",
  "Chartered Accountant",
  "Bank Employee",
  "Business Owner",
  "Entrepreneur",
  "Manager",
  "Sales Executive",
  "Marketing Executive",
  "Government Employee",
  "Civil Servant",
  "Police",
  "Army",
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Lawyer",
  "Advocate",
  "Judge",
  "Scientist",
  "Researcher",
  "Engineer",
  "Architect",
  "Electrician",
  "Plumber",
  "Mechanic",
  "Driver",
  "Farmer",
  "Cow Protection Service",
  "Cook",
  "Chef",
  "Temple Service",
  "Pujari",
  "Kirtaniya",
  "Preacher",
  "Counsellor",
  "Social Worker",
  "Administrator",
  "Clerk",
  "Receptionist",
  "HR Professional",
  "Data Entry Operator",
  "Freelancer",
  "Consultant",
  "Artist",
  "Musician",
  "Singer",
  "Actor",
  "Influencer",
  "Journalist",
  "Media Professional",
  "Event Manager",
  "Security Guard",
  "Housewife",
  "Retired",
  "Unemployed",
  "Other",
]);

export const Services = toOptions([
  "Book Distribution",
  "Harinam Sankirtan",
  "Kirtan",
  "Mridanga",
  "Kartal",
  "Harmonium",
  "Cooking",
  "Deity Worship",
  "Pujari Service",
  "Flower Service",
  "Garland Making",
  "Cleaning",
  "Temple Maintenance",
  "Guest Reception",
  "Preaching",
  "Counselling",
  "Youth Preaching",
  "College Preaching",
  "Children Preaching",
  "Bhagavatam Class",
  "Bhagavad-gita Class",
  "Public Speaking",
  "Translation",
  "Content Writing",
  "Social Media Service",
  "Graphic Design",
  "Photography",
  "Videography",
  "Video Editing",
  "Audio Management",
  "Stage Management",
  "Event Management",
  "Fundraising",
  "Donation Collection",
  "Administration",
  "Accounting",
  "Data Entry",
  "Website Management",
  "Software Development",
  "Technical Support",
  "Transport Service",
  "Driving",
  "Security Service",
  "Medical Assistance",
  "Cow Protection",
  "Farming",
  "Gardening",
  "Prasadam Distribution",
  "Book Stall Service",
  "Festival Coordination",
  "Decoration",
  "Hospitality",
  "Volunteer Coordination",
  "Cleaning Utensils",
  "Annadanam Service",
  "Outreach",
  "Library Service",
  "Office Management",
  "Store Management",
  "Maintenance",
  "Electric Work",
  "Plumbing",
  "Carpentry",
  "Tailoring",
  "Other",
]);
